### ISSUE TITLE
isx pr指令无法正常提交pr信息

### ISSUE THREAD

**Issue by fanciNater** [isxcode/isx-cli#193]
<img width="325" alt="image" src="https://github.com/isxcode/isx-cli/assets/53074025/9ec17f81-dd2b-4a40-9278-63bec54b806f">

**Comment by ispong** [comment]
![image](https://github.com/isxcode/isx-cli/assets/34756621/50224518-0edb-46c1-b1fe-2b18fd5b83c8)
![image](https://github.com/isxcode/isx-cli/assets/34756621/2ac4d48d-4b8a-41d7-8486-4056ec2ec9c4)
![image](https://github.com/isxcode/isx-cli/assets/34756621/92285472-9e9a-448b-b1d1-03aa26cea178)
