### ISSUE TITLE
isx clean会直接删除~/.zhiqingyun目录，给出确认提示

### ISSUE THREAD

**Issue by ispong** [isxcode/isx-cli#214]

**Comment by ispong** [comment]
![image](https://github.com/user-attachments/assets/fd7ca36f-ae2a-4e95-82b4-27205cc967d2)

不要直接删除~/.zhiqingyun，让使用者确认一下再删除

**Comment by EchoJamie** [comment]
效果预览:
<img width="455" alt="Screenshot 2024-10-06 at 06 41 50" src="https://github.com/user-attachments/assets/0bdd5f65-60e2-457f-88bc-602df1391b4a">
