### ISSUE TITLE
isx home命令，无法直接跳转到项目目录下

### ISSUE THREAD

**Issue by ispong** [isxcode/isx-cli#32]

**Comment by EchoJamie** [comment]
要切换调用Go程序的进程的当前工作目录，Go程序本身是无法直接实现的。进程的当前工作目录是由调用Go程序的父进程所控制的，Go程序无法直接修改其父进程的属性。

**Comment by ispong** [comment]
> 要切换调用Go程序的进程的当前工作目录，Go程序本身是无法直接实现的。进程的当前工作目录是由调用Go程序的父进程所控制的，Go程序无法直接修改其父进程的属性。

再想想看是否有别的办法

**Comment by ispong** [comment]
先打印路径，让用户自己跳转
